name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to VPS
      env:
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        sudo apt-get install sshpass
        sshpass -p $SERVER_PASSWORD ssh $SERVER_USER@$SERVER_IP "mkdir -p /home/mathieu/pianoai/api"
        sshpass -p $SERVER_PASSWORD scp -o StrictHostKeyChecking=no app.py required.txt $SERVER_USER@$SERVER_IP:/home/mathieu/pianoai/api
        sshpass -p $SERVER_PASSWORD ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /home/mathieu/pianoai/api && sudo service pianoai stop && python3 -m venv venv && . venv/bin/activate && pip install -U pip && pip install -U -r required.txt && sudo service pianoai start"
