name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          rm -rf /home/mathieu/pianoai/api
          mkdir -p /home/mathieu/pianoai/api
          chown -R ${{ secrets.SERVER_USER }} /home/mathieu/pianoai/api
          chmod -R 755 /home/mathieu/pianoai/api

    - name: Copy code to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: '.'
        target: '/home/mathieu/pianoai/api'

    - name: Set up Python environment and run the application on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /home/mathieu/pianoai/api
          python3 -m venv venv
          source venv/bin/activate
          pip install -U pip
          pip install flask
          pip install flask_restful
          pip install flask_cors
          pip install tensorflow
          pip install tflearn
          pip install gevent
          pip install gunicorn
          sudo service pianoai stop
          sudo service pianoai start
