name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy code to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: '.'
        target: '/home/mathieu/pianoai'

    - name: Set up Python environment and run the application on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /home/mathieu/pianoai
          python3 -m venv venv
          source venv/bin/activate
          pip install -U pip
          pip install -U -r required.txt
          sudo systemctl stop pianoai
          sudo systemctl start pianoai
